apiVersion: v1
kind: Service
metadata:
  name: bubble-sort-service
  labels:
    app: bubble-sort
spec:
  type: NodePort
  selector:
    app: bubble-sort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31001
      name: metrics          
